language: php
php:
- 5.6
- 7.0
jobs:
  include:
  - php: 7.0
    env: KEY=VALUE
  allow_failures:
  - php: 7.0
    env: KEY=VALUE

before_script:
  - git clone --depth 1 git://github.com/Superschool/Superschool.git ../Superschool && cd ../Superschool
script:  
  - ./Superschool/Superschool --stderr
 